function init_paths()

    addpath('./common', ...
            './model_suh', ...
            './model_ovgu_simplified', ...
            './mpc', ...
            './ode_modelling' ...
            );

end
